### ISSUE TITLE
we can't change the batch_size!

### ISSUE THREAD

**Issue by nijingxiong** [TimDettmers/ConvE#30]
When I modify the model's batch_size with the command line, the program will report an error.

 
![1534582444 1](https://user-images.githubusercontent.com/29858821/44297639-6c303f80-a307-11e8-8453-a6da9dafce7c.jpg)

**Comment by TimDettmers** [comment]
Thank you for your bug report!

It seems that the data on your disk is smaller than the data for a mini-batch, can that be? If you rerun the full data preprocessing pipeline, do you still have the error? What also might help is to change the seed that you pass into the StreamBatcher:
```python
    train_batcher = StreamBatcher(Config.dataset, 'train', Config.batch_size, randomize=True, keys=input_keys, seed=88888888)
```

Furthermore, it would be helpful if you can replicate this bug with an existing dataset and configuration so that I can replicate it. With this I should be able to fix the bug quickly.

**Comment by TimDettmers** [comment]
There were some issues with the batch size in the evaluation procedure. The training and test batch size can now also be different. See 5feb358eb7dbd1f534978cdc4c20ee0bf919148a for details.

I do not think this addresses the issue, but without further information, I am not able to replicate the error above.
