### ISSUE TITLE
Problem with batching on YAGO3-10

### ISSUE THREAD

**Issue by wiseodd** [TimDettmers/ConvE#5]
I encountered an error in the batching.
This always happens in when I run on YAGO3-10 (after ca. 6 epochs).

I use batch size of 128.

```bash
Exception in thread Thread-4:
Traceback (most recent call last):
  File "miniconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "ConvE/src/spodernet/spodernet/preprocessing/batching.py", line 154, in run
    start = self.rdm.randint(0, n-self.stream_batcher.batch_size+1)
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high
```

**Comment by TimDettmers** [comment]
Thanks for reporting the bug here. I will work on this tomorrow.

For now, you can adjust the `samples_per_file` parameter of the `StreamToHDF5` processor. You can edit the [main.py line 88](https://github.com/TimDettmers/ConvE/blob/master/main.py#L88) for this, the larger the more unlikely will this error occur. Another way to prevent this (although much more unreliable) is to change the random seed of the `StreamBatcher` via the `seed` parameter.

**Comment by wiseodd** [comment]
Thanks for the workaround.

I observed that during training, GPU utilization is very low, mostly near in 0-20% range with occasional spike to ~50%.
Increasing `samples_per_file` as per your instruction makes training longer.
Hence, I think the performance is bottlenecked by data loading.

Did you get the same behavior?
Or is there anyway to fix this?

**Comment by TimDettmers** [comment]
I could replicate the bug and it is now fixed — thanks again for reporting the issue. You need to update your `spodernet` repo and run `python setup.py install` in order to get the updates. You can also just delete the `src` folder and re-run `pip install -r requirement.txt`.

I also looked into the performance problems for large `sample_per_file` values and now extended the cache to be only cleaned after a certain threshold is reached (by default this is now 4GB of data; YAGO10-3 is about 400MB of data). From my tests, I confirm that these issues are fixed now.

The low utilization issues stem mainly from the large label conversion. The labels are loaded (ids) and converted into a multi-hot vector, for example `[0 0 0 0 1 0 0 1 0 .. 0 0 1 1 1 0]`. For YAGO3-10 the multi-hot vectors are quite large, in total about 40GB and so I load the ids and convert them at run-time in background threads asynchronously. While this improves efficiency over naive main-thread conversion this is far from optimal, but I think this is the best solution since few people have +48 GB of RAM in their machine to hold the pre-converted labels and I do not want to make this a requirement in order to run YAGO3-10 out of the box. Otherwise, low utilization can come from the small model. ConvE has a very small convolutional and hidden layer and only the output layer can saturate the GPU fully and this may also causes part of the low utilization.

If there are any other issues just let me know by opening a new issue.

Thanks again!
