### ISSUE TITLE
A question in evalution.py

### ISSUE THREAD

**Issue by nxznm** [TimDettmers/ConvE#58]
Hello, sorry to bother you, I want to ask a question about the code in evalution.py. At code [line](https://github.com/TimDettmers/ConvE/blob/5feb358eb7dbd1f534978cdc4c20ee0bf919148a/evaluation.py#L51) here `pred1[i][filter1] = 0.0`, I think filter1's size is `1*multi_key_length['e2_multi1']`, so it will have many numbers that are `-1`. So `pred1[i][filter1] = 0.0` will almost make the prediction of the last entity be zero every time. If so, I think the evaluation is not exactly right, although it has little impact on the final evaluation result.
I want to know if I'm wrong about this. I look forward to your reply. Thanks!

**Comment by TimDettmers** [comment]
This is the evaluation for the filtered setting as described in the appendix of the paper and as introduced by `Bordes et al., 2013`. The `filter1` and `filter2` contain all _positive_  triples (that is all correct triples).

 For example, if we have (Best actor, awarded to, X) then X can have many correct answers but the test triple might also want to see "Leonardo Di Carpio" for example. However, "Tom Hanks" is also correct and should not be penalized for this prediction. So what we do is that we rank "Tom Hanks" lower than all other triples so that it does not affect the results. This "filters" this triple from the testing process and thus constitutes the filtered setting.

Does this make sense?

**Comment by nxznm** [comment]
It does make sense. Thanks for your patience!
