### ISSUE TITLE
Clarification on Figure. 1 in the paper

### ISSUE THREAD

**Issue by yunchengwang** [TimDettmers/ConvE#65]
Hi Tim,

I recently read your paper about ConvE, and it's a wonderful work! However, I have a question that needs to be clarified in Figure 1. that why is the shape of the feature maps (3, 3)? I am assuming the 2D embeddings are convolved with 3x3 kernels and zero-padding is adopted. It will result in the feature maps having the same dimension as the input embeddings, which is (4, 2). Please correct me if I misunderstand anything. I couldn't figure out myself and need some of your inspiration. Thanks a lot!

**Comment by TimDettmers** [comment]
Your understanding is completely right, the figure is a bit confusing if you see it in this way. The figure was meant as a visual aid rather than an accurate depiction. When I made the figure I did not think about its correctness in this sense of feature map dimension and just thought "people should recognize that these are feature maps". It is a good point and I will keep these details in mind when I work on future figures.
