### ISSUE TITLE
question about the model of the convE

### ISSUE THREAD

**Issue by zyqdragon** [TimDettmers/ConvE#72]
There is " x = torch.mm(x, self.emb_e.weight.transpose(1,0))" in the model.py. What is the function of the code?

**Comment by TimDettmers** [comment]
Here the problem is that we have features of size `dim1` and we want to compute a score for each of the `dim2` entity embeddings. To do that, we can either project the features from `dim1` to `dim2` or we can multiply with the entire entity matrix which has size `dim2 x dim1`. This is the exact same way how we compute the output in language models. Using the entity embedding matrix yields better performance than computing a score for each entity embedding through a projection (just like in language modeling).

So the ultimate purpose of this operation is to get a score for each entity embedding and multiplying by the entity matrix is better than a learned projection matrix.

**Comment by zyqdragon** [comment]
great work!
