### ISSUE TITLE
Source and original format of kinship.tar.gz

### ISSUE THREAD

**Issue by samehkamaleldin** [TimDettmers/ConvE#8]
In your version of the kinship dataset, it's formatted like the following:
```
Term2	Person58	Person72
Term20	Person48	Person49
Term7	Person39	Person94
Term16	Person91        Person4
Term13	Person93	Person95
Term8	Person70        Person12
Term13	Person61        Person77
Term16	Person36	Person81
```
I wonder what is the original values of `Term#` relations, so I wonder what is the source of kinship dataset?  Also, I assume that this format is `Predicate, Subject, Object`. Do you consider rearranging columns before feeding data to the model? 

Thanks a lot.

**Comment by TimDettmers** [comment]
I think this was an error on my part — this is basically ther wrong data. I think I swaped columns with a bash command, but I never had a script in the repo so that for other people it would not work. There was another issue with the dataset having different splits than other public versions of the datasets. I fixed both issues and now the data should behave like other dataset. Thank you for spotting this mistake!
